            - الاسم: خدمة النشر المستمر لـ Armory
  # يمكنك التثبيت على الالتزام الدقيق أو الإصدار.
  # الاستخدامات: armory/cli-deploy-action@36fc96b3e295e960d22f96513ef781bb9865a87c
  الاستخدامات: armory/cli-deploy-action@v1.0.0
  مع:
    # المسار إلى ملف YAML للتكوين المستخدم لتكوين النشر الخاص بك
    المسار إلى الملف:
    # وسيطات إضافية لأمر بدء النشر
    اسم التطبيق: # اختياري
    # معلمات سياق إضافية لأمر بدء النشر
    addContext: # اختياري
    # معرف العميل لـ Armory Cloud
    معرف العميل:
    # ClientSecret لـ Armory Cloud
    سر العميل:
    # الفئة المستهدفة من الطلبات التي ستستخدم رمز مصادقة Armory Cloud الخاص بك. هل deployHostUrl افتراضيًا؟
    الجمهور: # اختياري، الافتراضي هو https://api.cloud.armory.io
    # عنوان URL لمزود مصادقة Armory Cloud
    tokenIssuerUrl: # اختياري، الافتراضي هو https://auth.cloud.armory.io/oauth
    # موقع واجهة برمجة تطبيقات Armory Cloud التي ستتولى عملية النشر الخاصة بك
    deployHostUrl: # اختياري، الافتراضي هو api.cloud.armory.io
          
